### ISSUE TITLE
How much of this is working?

### ISSUE THREAD

**Issue by frohro** [df7cb/SoapyIcomIQ#1]
Hi,
I'm looking for a simple SoapySDR driver to use as an example, and I came across this.  Is it working?  If so it might be a good example for me to start from for my QSD SDR receiver.
TNX & 73,
Rob
KL7NA

**Comment by df7cb** [comment]
Hi Rob,

basic IQ streaming works, but it's really alpha quality, i.e. I haven't had time to polish anything, and it can't even set or query the frequency yet.

If you want to start a new driver for a different device, there's template in the soapysdr source code that's probably better to base on. (I started from rtlsdr in the assumption it would be simple, but it's really not.)

The problem is that you can either pass simple blocks of IQ samples through (easy) or go full async for better performance which is quite complex to get right and also isn't a simple extension of the simple approach so needs some architectural juggling (that I haven't done yet).

Cheers,
Christoph DF7CB

**Comment by frohro** [comment]
Thank you Christoph!  
That is very helpful.  
Rob
